-- Run once for a new Supabase project.
-- Existing projects should run supabase/schema.sql instead.

create table public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('INCOME', 'EXPENSE')),
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(10, 2) not null check (amount > 0),
  transaction_date date not null,
  category text not null check (char_length(category) between 1 and 60),
  created_at timestamptz not null default now()
);
