-- Run this script once in the Supabase SQL Editor.
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('INCOME', 'EXPENSE')),
  account text not null default 'BANK' check (account in ('BANK', 'PAYPAL')),
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(10, 2) not null check (amount > 0),
  transaction_date date not null,
  category text not null check (char_length(category) between 1 and 60),
  created_at timestamptz not null default now()
);

alter table public.transactions
  add column if not exists account text not null default 'BANK';

alter table public.transactions
  drop constraint if exists transactions_account_check;

alter table public.transactions
  add constraint transactions_account_check check (account in ('BANK', 'PAYPAL'));

alter table public.transactions enable row level security;

drop policy if exists "Members can read transactions" on public.transactions;
create policy "Members can read transactions"
  on public.transactions for select
  to authenticated
  using (true);

drop policy if exists "Members can add transactions" on public.transactions;
create policy "Members can add transactions"
  on public.transactions for insert
  to authenticated
  with check (true);

drop policy if exists "Members can update transactions" on public.transactions;
create policy "Members can update transactions"
  on public.transactions for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Members can delete transactions" on public.transactions;
create policy "Members can delete transactions"
  on public.transactions for delete
  to authenticated
  using (true);
