-- Run this script once in the Supabase SQL Editor.
create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  type text not null check (type in ('INCOME', 'EXPENSE')),
  account text not null default 'BANK' check (account in ('BANK', 'PAYPAL')),
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(10, 2) not null check (amount > 0),
  transaction_date date not null,
  category text not null check (char_length(category) between 1 and 60),
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id),
  deleted_at timestamptz,
  deleted_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.transactions
  add column if not exists account text not null default 'BANK';

alter table public.transactions
  drop constraint if exists transactions_account_check;

alter table public.transactions
  add constraint transactions_account_check check (account in ('BANK', 'PAYPAL'));

alter table public.transactions add column if not exists updated_at timestamptz not null default now();
alter table public.transactions add column if not exists updated_by uuid references auth.users(id);
alter table public.transactions add column if not exists deleted_at timestamptz;
alter table public.transactions add column if not exists deleted_by uuid references auth.users(id);

alter table public.transactions enable row level security;

drop policy if exists "Members can read transactions" on public.transactions;
create policy "Members can read transactions"
  on public.transactions for select
  to authenticated
  using (true);

drop policy if exists "Members can add transactions" on public.transactions;
create policy "Members can add transactions"
  on public.transactions for insert
  to authenticated
  with check (true);

drop policy if exists "Members can update transactions" on public.transactions;
create policy "Members can update transactions"
  on public.transactions for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Members can delete transactions" on public.transactions;

create or replace function public.set_transaction_audit_fields()
returns trigger
language plpgsql
security invoker
as $$
begin
  new.updated_at = now();
  new.updated_by = auth.uid();
  if new.deleted_at is not null and old.deleted_at is null then
    new.deleted_by = auth.uid();
  end if;
  return new;
end;
$$;

drop trigger if exists transactions_audit on public.transactions;
create trigger transactions_audit
before update on public.transactions
for each row execute function public.set_transaction_audit_fields();
